/*	This work is licensed under Creative Commons GNU LGPL License.

	License:  http://creativecommons.org/licenses/LGPL/2.1/
   Version:  0.9
	Author:   Stefan Goessner/2006
	Web:      http://goessner.net/ 
   Modified: ThisAMJ 2021

   Minified by javascript-minifier.com
*/
function xml2json(e){var n={toObj:function(e){var t={};if(1==e.nodeType){if(e.attributes.length)for(var r=0;r<e.attributes.length;r++)t["@"+e.attributes[r].nodeName]=(e.attributes[r].nodeValue||"").toString();if(e.firstChild){for(var o=0,i=0,a=!1,l=e.firstChild;l;l=l.nextSibling)1==l.nodeType?a=!0:3==l.nodeType&&l.nodeValue.match(/[^ \f\n\r\t\v]/)?o++:4==l.nodeType&&i++;if(a)if(o<2&&i<2){n.removeWhite(e);for(l=e.firstChild;l;l=l.nextSibling)3==l.nodeType?t["#text"]=n.escape(l.nodeValue):4==l.nodeType?t["#cdata"]=n.escape(l.nodeValue):t[l.nodeName]?t[l.nodeName]instanceof Array?t[l.nodeName][t[l.nodeName].length]=n.toObj(l):t[l.nodeName]=[t[l.nodeName],n.toObj(l)]:t[l.nodeName]=n.toObj(l)}else e.attributes.length?t["#text"]=n.escape(n.innerXml(e)):t=n.escape(n.innerXml(e));else if(o)e.attributes.length?t["#text"]=n.escape(n.innerXml(e)):t=n.escape(n.innerXml(e));else if(i)if(i>1)t=n.escape(n.innerXml(e));else for(l=e.firstChild;l;l=l.nextSibling)t["#cdata"]=n.escape(l.nodeValue)}e.attributes.length||e.firstChild||(t=null)}else 9==e.nodeType?t=n.toObj(e.documentElement):alert("unhandled node type: "+e.nodeType);return t},toJson:function(e,t,r){var o=t?'"'+t+'"':"";if(e instanceof Array){for(var i=0,a=e.length;i<a;i++)e[i]=n.toJson(e[i],"",r+"\t");o+=`${t?":[":"["}${e.length>1?`\n${r}\t${e.join(`,\n${r}\t`)}\n${r}`:e.join("")}]`}else if(null==e)o+=(t&&":")+"null";else if("object"==typeof e){var l=[];for(var d in e)l[l.length]=n.toJson(e[d],d,r+"\t");o+=(t?":{":"{")+(l.length>1?"\n"+r+"\t"+l.join(",\n"+r+"\t")+"\n"+r:l.join(""))+"}"}else o+="string"==typeof e?(t&&":")+'"'+e.toString()+'"':(t&&":")+e.toString();return o},innerXml:function(e){var n="";if("innerHTML"in e)n=e.innerHTML;else for(var t=function(e){var n="";if(1==e.nodeType){n+="<"+e.nodeName;for(var r=0;r<e.attributes.length;r++)n+=" "+e.attributes[r].nodeName+'="'+(e.attributes[r].nodeValue||"").toString()+'"';if(e.firstChild){n+=">";for(var o=e.firstChild;o;o=o.nextSibling)n+=t(o);n+="</"+e.nodeName+">"}else n+="/>"}else 3==e.nodeType?n+=e.nodeValue:4==e.nodeType&&(n+="<![CDATA["+e.nodeValue+"]]>");return n},r=e.firstChild;r;r=r.nextSibling)n+=t(r);return n},escape:function(e){return e.replace(/[\\]/g,"\\\\").replace(/[\"]/g,'\\"').replace(/[\n]/g,"\\n").replace(/[\r]/g,"\\r")},removeWhite:function(e){e.normalize();for(var t=e.firstChild;t;t=t.nextSibling)3==t.nodeType?t.nodeValue.match(/[^ \f\n\r\t\v]/)||e.removeChild(t):1==t.nodeType&&n.removeWhite(t);return e}};return 9==e.nodeType&&(e=e.documentElement),JSON.parse(`{${n.toJson(n.toObj(e),e.nodeName,"\t")}}`)}
